package iv

import (
	"math"
	"testing"
	"time"

	"volatility-engine/internal/domain/market"
	"volatility-engine/internal/quant/pricing"
)

// TestRoundTrip tests that IV Solver recovers the original volatility
// when fed a price generated by the pricing engine with that volatility.
func TestRoundTrip(t *testing.T) {
	// Test parameters
	testCases := []struct {
		name    string
		optType market.OptionType
		F       float64 // Forward
		K       float64 // Strike
		T       float64 // TTE years
		r       float64 // Risk-free rate
		sigmaIn float64 // Input volatility to recover
	}{
		{"ATM Call", market.Call, 25320.0, 25300.0, 0.0137, 0.06, 0.18},
		{"ATM Put", market.Put, 25320.0, 25300.0, 0.0137, 0.06, 0.18},
		{"OTM Call", market.Call, 25320.0, 25500.0, 0.0137, 0.06, 0.20},
		{"ITM Put", market.Put, 25320.0, 25500.0, 0.0137, 0.06, 0.20},
		{"Low Vol", market.Call, 25320.0, 25300.0, 0.0137, 0.06, 0.10},
		{"High Vol", market.Call, 25320.0, 25300.0, 0.0137, 0.06, 0.35},
	}

	solver := NewSolver(DefaultSettings())

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			// Step 1: Price with known sigma
			pCtx := pricing.PricingContext{
				Type:           tc.optType,
				S:              tc.F, // Forward model
				K:              tc.K,
				T:              tc.T,
				R:              tc.r,
				Q:              0,
				Sigma:          tc.sigmaIn,
				IsForwardModel: true,
			}
			pRes := pricing.Calculate(pCtx)
			modelPrice := pRes.Price

			// Step 2: Solve IV from that price
			ivReq := market.IVRequest{
				ID:   "roundtrip_test",
				AsOf: time.Now(),
				Instrument: market.IVInstrument{
					Underlying: "TEST",
					Expiry:     "2026-02-05",
					Strike:     tc.K,
					Type:       tc.optType,
				},
				Market: market.IVMarket{
					MarkPrice:  modelPrice,
					MarkSource: "MODEL",
					Bid:        modelPrice * 0.98,
					Ask:        modelPrice * 1.02,
					SpreadPct:  0.04,
				},
				Context: market.IVContext{
					Spot:          tc.F,
					Forward:       tc.F,
					ForwardSource: "MODEL",
					TTEYears:      tc.T,
				},
				Rates: market.Rates{
					RiskFreeRateCC: tc.r,
					DiscountFactor: math.Exp(-tc.r * tc.T),
				},
				Settings: DefaultSettings(),
			}

			ivRes := solver.Solve(ivReq)

			// Step 3: Verify
			if ivRes.Status != market.IVStatusConverged {
				t.Errorf("Solver did not converge: %s", ivRes.Status)
				return
			}

			// Check recovered sigma is close to input
			tolerance := 0.001 // 0.1% vol tolerance
			if math.Abs(ivRes.Result.ImpliedVol-tc.sigmaIn) > tolerance {
				t.Errorf("Round-trip failed: input σ=%.4f, recovered σ=%.4f, diff=%.6f",
					tc.sigmaIn, ivRes.Result.ImpliedVol, ivRes.Result.ImpliedVol-tc.sigmaIn)
			} else {
				t.Logf("✓ Round-trip passed: σ=%.4f → price=%.4f → IV=%.4f",
					tc.sigmaIn, modelPrice, ivRes.Result.ImpliedVol)
			}
		})
	}
}

// TestMarketReprice tests that solving IV from a market price and re-pricing
// with that IV gives back approximately the same price.
func TestMarketReprice(t *testing.T) {
	// Simulated market quotes (realistic NIFTY data)
	testCases := []struct {
		name    string
		optType market.OptionType
		strike  float64
		bid     float64
		ask     float64
		forward float64
		tte     float64
	}{
		{"ATM Call", market.Call, 25300, 280.0, 290.0, 25320.0, 0.0137},
		{"ATM Put", market.Put, 25300, 265.0, 275.0, 25320.0, 0.0137},
		{"OTM Call", market.Call, 25500, 120.0, 130.0, 25320.0, 0.0137},
		{"OTM Put", market.Put, 25100, 95.0, 105.0, 25320.0, 0.0137},
	}

	solver := NewSolver(DefaultSettings())

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			mid := (tc.bid + tc.ask) / 2.0
			r := 0.06
			df := math.Exp(-r * tc.tte)

			// Step 1: Solve IV from market mid
			ivReq := market.IVRequest{
				ID:   "market_test",
				AsOf: time.Now(),
				Instrument: market.IVInstrument{
					Underlying: "NIFTY",
					Expiry:     "2026-02-05",
					Strike:     tc.strike,
					Type:       tc.optType,
				},
				Market: market.IVMarket{
					MarkPrice:  mid,
					MarkSource: "MID",
					Bid:        tc.bid,
					Ask:        tc.ask,
					SpreadPct:  (tc.ask - tc.bid) / mid,
				},
				Context: market.IVContext{
					Spot:          tc.forward,
					Forward:       tc.forward,
					ForwardSource: "PUT_CALL_PARITY",
					TTEYears:      tc.tte,
				},
				Rates: market.Rates{
					RiskFreeRateCC: r,
					DiscountFactor: df,
				},
				Settings: DefaultSettings(),
			}

			ivRes := solver.Solve(ivReq)

			if ivRes.Status != market.IVStatusConverged {
				t.Errorf("Solver did not converge: %s", ivRes.Status)
				return
			}

			// Step 2: Re-price with solved IV
			pCtx := pricing.PricingContext{
				Type:           tc.optType,
				S:              tc.forward,
				K:              tc.strike,
				T:              tc.tte,
				R:              r,
				Q:              0,
				Sigma:          ivRes.Result.ImpliedVol,
				IsForwardModel: true,
			}
			pRes := pricing.Calculate(pCtx)

			// Step 3: Verify model price ≈ market mid
			priceErr := math.Abs(pRes.Price - mid)
			relErr := priceErr / mid

			if relErr > 0.001 {
				t.Errorf("Re-price mismatch: market mid=%.2f, model price=%.2f, err=%.4f (%.4f%%)",
					mid, pRes.Price, priceErr, relErr*100)
			} else {
				t.Logf("✓ Market re-price passed: mid=%.2f → IV=%.4f → price=%.4f (err=%.4f)",
					mid, ivRes.Result.ImpliedVol, pRes.Price, priceErr)
			}
		})
	}
}

// TestEdgeCases tests solver behavior on edge cases
func TestEdgeCases(t *testing.T) {
	solver := NewSolver(DefaultSettings())

	t.Run("Zero Price", func(t *testing.T) {
		ivReq := market.IVRequest{
			ID:   "zero_price",
			AsOf: time.Now(),
			Instrument: market.IVInstrument{
				Strike: 25000,
				Type:   market.Call,
			},
			Market: market.IVMarket{
				MarkPrice: 0,
			},
			Context: market.IVContext{
				Forward:  25000,
				TTEYears: 0.01,
			},
			Rates: market.Rates{
				RiskFreeRateCC: 0.06,
			},
			Settings: DefaultSettings(),
		}
		res := solver.Solve(ivReq)
		if res.Status != market.IVStatusNumeric {
			t.Errorf("Expected FAILED_NUMERIC for zero price, got %s", res.Status)
		}
	})

	t.Run("Price Out of Bounds (Too Low)", func(t *testing.T) {
		// Deep OTM call with price below intrinsic (impossible)
		ivReq := market.IVRequest{
			ID:   "oob_low",
			AsOf: time.Now(),
			Instrument: market.IVInstrument{
				Strike: 26000,
				Type:   market.Call,
			},
			Market: market.IVMarket{
				MarkPrice:  0.01, // Too low
				MarkSource: "MID",
			},
			Context: market.IVContext{
				Forward:  25000,
				TTEYears: 0.01,
			},
			Rates: market.Rates{
				RiskFreeRateCC: 0.06,
				DiscountFactor: 0.9994,
			},
			Settings: DefaultSettings(),
		}
		res := solver.Solve(ivReq)
		// For deep OTM with very small price, may still solve or hit bounds
		t.Logf("Deep OTM result: status=%s, IV=%.4f", res.Status, res.Result.ImpliedVol)
	})
}
